//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace KnightRider.ElectionTracker.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        private static ResourceManager resourceMan;

        private static CultureInfo resourceCulture;

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {}

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("KnightRider.ElectionTracker.Properties.Resources", typeof (Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap arrow_left {
            get {
                object obj = ResourceManager.GetObject("arrow_left", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap btnAdd_Image {
            get {
                object obj = ResourceManager.GetObject("btnAdd_Image", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap btnDelete_Image {
            get {
                object obj = ResourceManager.GetObject("btnDelete_Image", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap btnEdit_Image {
            get {
                object obj = ResourceManager.GetObject("btnEdit_Image", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap btnNew_Image {
            get {
                object obj = ResourceManager.GetObject("btnNew_Image", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap btnReset_Image {
            get {
                object obj = ResourceManager.GetObject("btnReset_Image", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap btnSave_Image {
            get {
                object obj = ResourceManager.GetObject("btnSave_Image", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap EditInformationHS {
            get {
                object obj = ResourceManager.GetObject("EditInformationHS", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap EditInformationHS1 {
            get {
                object obj = ResourceManager.GetObject("EditInformationHS1", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap EditTableHS {
            get {
                object obj = ResourceManager.GetObject("EditTableHS", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap EditTableHS1 {
            get {
                object obj = ResourceManager.GetObject("EditTableHS1", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap NewCardHS {
            get {
                object obj = ResourceManager.GetObject("NewCardHS", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap NewCardHS1 {
            get {
                object obj = ResourceManager.GetObject("NewCardHS1", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap page_gear {
            get {
                object obj = ResourceManager.GetObject("page_gear", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap resultset_next {
            get {
                object obj = ResourceManager.GetObject("resultset_next", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap resultset_previous {
            get {
                object obj = ResourceManager.GetObject("resultset_previous", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap saveHS {
            get {
                object obj = ResourceManager.GetObject("saveHS", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap saveHS1 {
            get {
                object obj = ResourceManager.GetObject("saveHS1", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap tick {
            get {
                object obj = ResourceManager.GetObject("tick", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Icon vote {
            get {
                object obj = ResourceManager.GetObject("vote", resourceCulture);
                return ((Icon) (obj));
            }
        }

        internal static Bitmap zoom_in {
            get {
                object obj = ResourceManager.GetObject("zoom_in", resourceCulture);
                return ((Bitmap) (obj));
            }
        }

        internal static Bitmap zoom_out {
            get {
                object obj = ResourceManager.GetObject("zoom_out", resourceCulture);
                return ((Bitmap) (obj));
            }
        }
    }
}