//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace edu.uwec.cs.cs355.group4.et.Properties {
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        private static Settings defaultInstance = ((Settings) (Synchronized(new Settings())));

        public static Settings Default {
            get { return defaultInstance; }
        }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue(
            "C:\\Documents and Settings\\dlotts\\My Documents\\Visual Studio 2005\\Projects\\ET\\ET\\e" +
            "du\\uwec\\et\\cfg\\Spring.xml")]
        public string SpringConfiguration {
            get { return ((string) (this["SpringConfiguration"])); }
        }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [SpecialSetting(SpecialSetting.ConnectionString)]
        [DefaultSettingValue("Data Source =\".\\MyDatabase1.sdf\"")]
        public string DB_1_ConnectionString {
            get { return ((string) (this["DB_1_ConnectionString"])); }
        }
    }
}